**1. What does Pandas stand for?**
- **Pandas** - An open-source Python package that is widely used
- Built on top of NumPy (supports 1+ D arrays)
- **Stands for either**: 
    1. Panel Data 
    2. Python Data Analysis
- Created by Wes McKinney in 2008


**2. What are the 2 collections used in Pandas?**
Series and data frames 


**3. Name 4 things Pandas can do for us.**
Data cleansing, data fill ,data normilization and data visialization and mrge and joinsinspectio loading and saving data 

**4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?**  inplace = true 

**5. What is a CSV?**
A file contains plan text and is well know format that can be ready by eveyone including pandas


**6. When cleaning data what values do we not like in our data?**  missing values null and duplicate values incorrect values

In [ ]:
# 7.Import NumPy, use one of the NumPy methods and create an array with a shape
# of (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np

data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

a_1 = np.arange (12,).reshape ((2, 3, 2))
a_1


In [ ]:
## 8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20
array = np.linspace(0, 20, 6)

print(array)

In [ ]:
## 9. Make a Deep Copy of the above array
dc_array = array.copy()

print(dc_array)

In [3]:
## 10.Concatenate these 3 arrays into a new array named 'newArray'..
#([[25, 16]])
        #([[11, 2], [13, 4]])
        #([[7, 81], [5, 6], [11, 12]])

array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((array1, array2, array3), axis=0)

print(newArray)


[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [4]:
## 11. Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(newArray, axis=0)

print(sortedArray)


[[ 5  2]
 [ 7  4]
 [11  6]
 [11 12]
 [13 16]
 [25 81]]


In [6]:
## 12.Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. 
#Print the 4 variables.

reshapedArray = np.array([(5, 2), (7, 4), (11, 6), (11, 12)])

# Unpack the tuples into 4 well-named variables
var1, var2, var3, var4 = reshapedArray

# Print the 4 variables
print("Variable 1:", var1)
print("Variable 2:", var2)
print("Variable 3:", var3)
print("Variable 4:", var4)


Variable 1: [5 2]
Variable 2: [7 4]
Variable 3: [11  6]
Variable 4: [11 12]


In [11]:
##13. Combined and sort the following arrays into one called 'comboArray' ...

#one = ([10, 11, 12, 13, 14, 15, 16, 17])
    #two = ([20, 21, 22, 23, 24, 25, 26, 27])
    #three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

import numpy as np

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

#Example  1:
# sorted_array = np.sort(one, two, three)

# combo_array = sorted_array

# print(combo_array)


#Example  2:
comboArray = np.concatenate((one, two, three))

sortedComboArray = np.sort(comboArray)

print(sortedComboArray)



[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [7]:
#14. Take 'comboArray' and perform the following slicing activities:
#print sec1 - the 2nd element
#print sec2 - all elements from the 3rd element to the last
#print sec3 - all elements from the 4th to the 14th elements
#print sec4 - the last 6 elements
#print sec5 - all element from #0 up to and including #15, 
#using the negative number method, i.e. taking a section from the end.
#print sec6 - from #20 every even element to the end
#print sec7 - from the last element moving forward, every 5th element.

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate([three, one, two])

print(comboArray)
#- print sec1 - the 2nd element

print(comboArray[1:2])
    
#- print sec2 - all elements from the 3rd element to the last

print(comboArray[2:])
    
#- print sec3 - all elements from the 4th to the 14th elements

print(comboArray[3:14])
    
#- print sec4 - the last 6 elements

print(comboArray[18:])
    
#- print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.

print(comboArray[-24:-10])
    
#- print sec6 - from #20 every even element to the end

print(comboArray[16::2])
    
#- print sec7 - from the last element moving backward, every 5th element.

print(comboArray[-1::-5])




[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[1]
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [ ]:
#15. Using Series, create a DataFrame that looks like this:

#| Ingredients | Quantity | # Unit 
# | Flour | 4 | cups | | Milk | 1 | cup | | Eggs | 2 | large |
#  | Spam | 1 | can |

#Name: Dinner, dtype: object

import pandas as pd

df = pd.DataFrame({
    'Ingredients': ['Flour', 'Milk', 'Eggs', 'Spam'],
    'Quantity': [4, 1, 2, 1],
    'Unit': ['cups', 'cup', 'large', 'can']
})

df 

In [8]:
#16. Take this data and create a DataFrame named studentData
#{'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
 #       'Height': [5.1, 6.2, 5.1, 5.2],
  #      'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
   #     'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    #    'Age': [21, 23, 24, 21],
     #  'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    #}

import pandas as pd

studentData = pd.DataFrame({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        })

studentData

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

In [10]:
#17. Add a new column to the DataFrame with the following deserts:
deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

studentData['desert']= deserts

In [ ]:
#18 Sort the 'studentData' DataFrame in Ascending order 
#-- Sorting by column 'Name' and then "address"
import pandas as pd
data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'],
    'deserts': ['ice cream', 'Cashew Fudge', 'waffles', 'Carrot Halwa']
}

# Create a DataFrame from the data dictionary
studentData = pd.DataFrame(data)

# Sort the DataFrame by 'Name' and then 'address' in ascending order
studentData = studentData.sort_values(by=['Name', 'address'], ascending=[True, True])

print(studentData)

In [ ]:
## 19. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

#df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

import pandas as pd

df = pd.DataFrame({'Cows': [12, 20], 
                   'Goats': [22, 19]}, 
                   index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv')

df= pd.read_csv('cows_and_goats.csv')

df

In [11]:
#20.(A) Using Pandas, make your own .CSV file with data on vegetables and save it. 
#(B) Using Pandas, make a change to your CSV file,
 # and save a copy with a different name

import pandas as pd

# Create a DataFrame with vegetable data
vegetables_data = {
    'Vegetable': ['Carrot', 'Broccoli', 'Spinach', 'Tomato', 'Cucumber'],
    'Color': ['Orange', 'Green', 'Green', 'Red', 'Green'],
    'Taste': ['Sweet', 'Crunchy', 'Leafy', 'Juicy', 'Refreshing']
}

vegetables_df = pd.DataFrame(vegetables_data)



# Save the DataFrame to a CSV file
vegetables_df.to_csv('vegetables.csv')

vegetables_df


Vegetable   Color       Taste
0    Carrot  Orange       Sweet
1  Broccoli   Green     Crunchy
2   Spinach   Green       Leafy
3    Tomato     Red       Juicy
4  Cucumber   Green  Refreshing

In [9]:
vegetables_df = pd.read_csv('vegetables.csv')

# Make changes to the DataFrame (e.g., add a new column)
vegetables_df['Nutrition'] = ['Healthy', 'Nutrient-Rich', 'Low-Calorie', 'Vitamin-C', 'Hydrating']

# Save the modified DataFrame to a new CSV file with a different name
mod_veg_df = 'vegetables_modified.csv'
vegetables_df.to_csv(mod_veg_df)